# Generated by Django 2.2.7 on 2020-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='教师审核',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenheStatu', models.CharField(default='', max_length=50, verbose_name='审核状态')),
                ('teacherid', models.CharField(default='', max_length=50, verbose_name='老师编号')),
                ('teachername', models.CharField(default='', max_length=50, verbose_name='老师姓名')),
            ],
        ),
    ]
